src/Presentation/TheCastle.WebUI/Controllers/ArmiesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheCastle.Application.Interfaces;
using TheCastle.Domain.Entities;

namespace TheCastle.Web.Controllers
{
    [Authorize]
    public class ArmiesController : Controller
    {
        private readonly ICastleService _castleService;
        private readonly IArmyService _armyService;

        public ArmiesController(ICastleService castleService,
                                IArmyService armyService)
        {
            _castleService = castleService;
            _armyService = armyService;
        }

        // GET: Armies
        public async Task<IActionResult> Index()
        {
            return View(await _armyService.GetAll().ToListAsync());
        }

        // GET: Armies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                var army = await _armyService.GetOneWithDetails(id);
                return View(army);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        // GET: Armies/Create
        public IActionResult Create()
        {
            var castleList = _castleService.GetAll().OrderBy(x => x.Name);

            ViewData["CastleId"] = new SelectList(castleList, "Id", "Id");
            return View();
        }

        // POST: Armies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Army army)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _armyService.Create(army);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                throw;
            }

            var castleList = _castleService.GetAll().OrderBy(x => x.Name);

            ViewData["CastleId"] = new SelectList(castleList, "Id", "Id");
            return View(army);
        }

        // GET: Armies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                var army = await _armyService.GetOne(id);

                if (army == null)
                {
                    return NotFound();
                }

                return View(army);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        // POST: Armies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Army army)
        {
            if (id != army.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _armyService.Update(army);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArmyExists(army.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(army);
        }

        // GET: Armies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var army = await _armyService.GetOne(id);

            if (army == null)
            {
                return NotFound();
            }

            return View(army);
        }

        // POST: Armies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _armyService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ArmyExists(int id)
        {
            return _armyService.EntityExist(id);
        }
    }
}

src/Presentation/TheCastle.WebUI/Controllers/CastlesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheCastle.Application.Interfaces;
using TheCastle.Domain.Entities;

namespace TheCastle.Web.Controllers
{
    [Authorize]
    public class CastlesController : Controller
    {
        private readonly ICastleService _castleService;
        private readonly IArmyService _armyService;

        public CastlesController(ICastleService castleService,
                                 IArmyService armyService)
        {
            _castleService = castleService;
            _armyService = armyService;
        }

        // GET: Castles
        public async Task<IActionResult> Index()
        {
            var Castles =  await _castleService.GetAll()
                                               .Include(x => x.Army)
                                               .ToListAsync();

            return View(Castles);

            /* Scaffolded code
            var applicationDBContext = _castleService.Castles.Include(c => c.Army);
            return View(await applicationDBContext.ToListAsync());
            */
        }

        // GET: Castles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                var castle = await _castleService.GetOneWithDetails(id);
                return View(castle);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return NotFound();
            }

            /* Scaffolded code
            if (id == null)
            {
                return NotFound();
            }

            var castle = await _castleService.Castles
                .Include(c => c.Army)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (castle == null)
            {
                return NotFound();
            }

            return View(castle);
            */
        }

        // GET: Castles/Create
        public IActionResult Create()
        {
            var armyList = _armyService.GetAll().OrderBy(x => x.Name);

            ViewData["ArmyId"] = new SelectList(armyList, "Id", "Name");
            return View();

            /* Scaffolded code
            ViewData["ArmyId"] = new SelectList(_castleService.Armies, "Id", "Id");
            return View();
            */
        }

        // POST: Castles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,ArmyId,Id")] Castle castle)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _castleService.Create(castle);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                throw;
            }

            var armyList = _armyService.GetAll().OrderBy(x => x.Name);

            ViewData["ArmyName"] = new SelectList(armyList, "Id", "Name");
            return View(castle);

            /* Scaffolded code
            if (ModelState.IsValid)
            {
                _castleService.Add(castle);
                await _castleService.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArmyId"] = new SelectList(_castleService.Armies, "Id", "Id", castle.ArmyId);
            return View(castle);
            */
        }

        // GET: Castles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                var castle = await _castleService.GetOne(id);

                if (castle == null)
                {
                    return NotFound();
                }

                var armyList = _armyService.GetAll().OrderBy(x => x.Name);
                ViewData["ArmyId"] = new SelectList(armyList, "Id", "Name", castle.ArmyId);

                return View(castle);
            }
            catch (Exception)
            {
                return NotFound();
            }

            /* Scaffolded code
            if (id == null)
            {
                return NotFound();
            }

            var castle = await _castleService.Castles.FindAsync(id);
            if (castle == null)
            {
                return NotFound();
            }
            ViewData["ArmyId"] = new SelectList(_castleService.Armies, "Id", "Id", castle.ArmyId);
            return View(castle);
            */
        }

        // POST: Castles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,ArmyId,Id")] Castle castle)
        {
            if (id != castle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _castleService.Update(castle);
                    //_castleService.Update(castle);
                    //await _castleService.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CastleExists(castle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var armyList = _armyService.GetAll().OrderBy(x => x.Name);
            ViewData["ArmyId"] = new SelectList(armyList, "Id", "Name", castle.ArmyId);

            //ViewData["ArmyId"] = new SelectList(_castleService.Armies, "Id", "Id", castle.ArmyId);
            return View(castle);
        }

        // GET: Castles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var castle = await _castleService.GetOne(id);

            if (castle == null)
            {
                return NotFound();
            }

            return View(castle);

            /* Scaffolded code
            if (id == null)
            {
                return NotFound();
            }

            var castle = await _castleService.Castles
                .Include(c => c.Army)
                .FirstOrDefaultAsync(m => m.Id == id);
            */
        }

        // POST: Castles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _castleService.Delete(id);
            return RedirectToAction(nameof(Index));

            /* Scaffolded code
            var castle = await _castleService.Castles.FindAsync(id);
            _castleService.Castles.Remove(castle);
            await _castleService.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            */
        }

        private bool CastleExists(int id)
        {
            return _castleService.EntityExist(id);

            /* Scaffolded code
            return _castleService.Castles.Any(e => e.Id == id);
            */
        }
    }
}

src/Presentation/TheCastle.WebUI/Views/Armies/Create.cshtml
@model TheCastle.Domain.Entities.Army

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Army</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Presentation/TheCastle.WebUI/Views/Armies/Delete.cshtml
@model TheCastle.Domain.Entities.Army

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Army</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/Presentation/TheCastle.WebUI/Views/Armies/Details.cshtml
@model TheCastle.Domain.Entities.Army

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Army</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<h3>Castles</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Castle
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var castle in Model.Castles)
        {
            <tr>
                <td>
                    <a class="text-dark" asp-controller="Castles" asp-action="Details" asp-route-id="@castle.Id">
                        @Html.DisplayFor(modelItem => castle.Name)
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/Presentation/TheCastle.WebUI/Views/Armies/Edit.cshtml
@model TheCastle.Domain.Entities.Army

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Army</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Presentation/TheCastle.WebUI/Views/Armies/Index.cshtml
@model IEnumerable<TheCastle.Domain.Entities.Army>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>